### ISSUE TITLE
[Proposal] Implement a 'Zero' Length Unit

### ISSUE THREAD

**Issue by LooserName404** [Bjorn-Strom/FSS#27]
When I have to set some property to 0, I think it's not the best option to put some length unit and set it to zero (like `(px 0)`). I think it would be better for readability to have some Zero length, or something in this line.

It would be something like

```fs
Margin.value (zero, px 10)
```

What do you think?

**Comment by Bjorn-Strom** [comment]
Hey @LooserName404,

Thanks for the suggestion!

I had actually implemented a "zero" length option earlier, but I removed it because I was worried that it might cause confusion across different unit types. For instance, different types of units have different valid zero values, such as all length units (px, em, rem) and angles (deg, rad, grad, turn) have 0 as a valid "zero" value, while time (s, ms) and resolution (dpi) have separate valid "zero" values and 0 is not valid for them. Frequency, if I ever decide to support that, might also have a different valid zero value.

Having said that, I completely agree that writing `px 0` everywhere is not only tedious but also ugly. So I would love to get a fix into the library.

As a quick fix you can add `let zero = px 0` to quickly remove the px 0  lines from your code. But it is not a good solution for all different unit types.

Do you have any suggestions for the API?

**Comment by LooserName404** [comment]
Looking at the codebase, I've noticed that the `ILengthPercentage` is in the `Units.fs` file, while other general interfaces are in `MasterTypes.fs`. Can I move it to this file? This way, we can have `Auto` implementing it, and then we can do the same for `Zero`.

What do you think?

**Comment by Bjorn-Strom** [comment]
Oh nicely spotted!
There is no reason for `ILengthPercentage` being in `Units.fs` instead of `MasterTypes.fs`.
We can surely move it and try to implement `Zero` that way. That is a good idea 👍

**Comment by Bjorn-Strom** [comment]
Closing with merge of #32 .
Good work, @LooserName404. Thank you so much for the contribution.
I will release this asap 👍
